logging:
  file:
    name: app.log
  level:
    org:
      springframework:
        web: INFO
    depavlo:
      walker: INFO
    depavlo.walker.service: INFO
  pattern:
    console: '%highlight(%-5level) %green(%C{1.}):%L - %msg%n%throwable'

